# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_calculator', '0002_auto_20160316_1805'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='datacenters',
        ),
        migrations.RemoveField(
            model_name='order',
            name='features',
        ),
        migrations.RemoveField(
            model_name='order',
            name='package',
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(to='pricing_calculator.Package'),
        ),
    ]
